# Generated by Django 6.0.6 on 2026-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmemory',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
    ]
