# Generated by Django 6.0.6 on 2026-07-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_chatsession_user_attachment_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
