# Generated by Django 6.0.6 on 2026-07-03 06:43

import conversation.models.admin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_chatsession_is_pinned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('tokens', models.IntegerField(default=100000)),
                ('msgs', models.IntegerField(default=1000)),
                ('upload', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'billing_plans',
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('context', models.IntegerField(default=100000)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'llm_models',
            },
        ),
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.CharField(default=conversation.models.admin.generate_short_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('server_type', models.CharField(default='sse', max_length=50)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('command', models.CharField(blank=True, default='', max_length=100)),
                ('args', models.CharField(blank=True, default='', max_length=500)),
                ('env_variables', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mcp_servers',
            },
        ),
        migrations.CreateModel(
            name='ProviderSettings',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('api_key_encrypted', models.BooleanField(default=False)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('request_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'provider_settings',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.CharField(default=conversation.models.admin.generate_short_id, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='open', max_length=50)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_tickets',
            },
        ),
    ]
