import pytest
import unittest.mock
from unittest.mock import AsyncMock, MagicMock
from conversation.utils.helpers import generate_uuid
from conversation.models.session import ChatSession
from conversation.llm_manager import LLMResponse

class MockTool:
    def __init__(self, name, description, inputSchema):
        self.name = name
        self.description = description
        self.inputSchema = inputSchema

class MockToolsList:
    def __init__(self, tools):
        self.tools = tools

class MockContentItem:
    def __init__(self, type_str: str, text_str: str):
        self.type = type_str
        self.text = text_str

@pytest.mark.django_db(transaction=True)
@pytest.mark.asyncio
async def test_conversation_manager_mcp_tool_loop(conversation_manager):
    session_id = generate_uuid()
    await conversation_manager.initialize_session(session_id, title=None)
    
    # 1. Mock stdio_client and ClientSession
    mock_mcp_session = AsyncMock()
    mock_mcp_session.__aenter__.return_value = mock_mcp_session
    mock_mcp_session.list_tools.return_value = MockToolsList([
        MockTool("execute_sql", "Execute read-only SQL queries", {"type": "object"})
    ])
    
    # Setup mock call_tool result containing the real sensitive data
    mock_item = MockContentItem("text", '[{"consumer_name": "Rohan Sen", "mobile_no": "9988776655"}]')
    
    mock_call_result = MagicMock()
    mock_call_result.content = [mock_item]
    mock_mcp_session.call_tool.return_value = mock_call_result
    
    # Setup stdio_client mock context manager
    mock_stdio = MagicMock()
    mock_stdio.__aenter__.return_value = (None, None)
    mock_stdio.__aexit__.return_value = None
    
    # 2. Mock Claude LLM Provider generate to return tool call first, then text response
    from anthropic.types import ToolUseBlock, TextBlock
    
    # We use a side_effect to return different responses on consecutive calls
    call_count = 0
    phone_token_box = [] # Will capture the token generated for the phone number
    
    async def mock_generate(*args, **kwargs):
        nonlocal call_count
        call_count += 1
        messages = kwargs.get("messages", [])
        
        if call_count == 1:
            # Capture the token generated for the user's phone number during step 1
            user_msg = messages[-1]["content"]
            user_msg_str = str(user_msg) if not isinstance(user_msg, str) else user_msg
            print(f"\n--- DEBUG: user_msg_str = {user_msg_str} ---")
            
            import re
            tokens = re.findall(r'<//PHONE-[a-f0-9]+//>', user_msg_str)
            assert len(tokens) > 0, "User prompt was not tokenized before sending to Claude!"
            phone_token = tokens[0]
            phone_token_box.append(phone_token)
            
            # First turn: Claude returns a tool use block containing the token
            tool_use_block = ToolUseBlock(
                id="call_1",
                name="execute_sql",
                input={"sql": f"SELECT consumer_name, mobile_no FROM consumer_master WHERE mobile_no = '{phone_token}'"},
                type="tool_use"
            )
            return LLMResponse(
                content="",
                prompt_tokens=100,
                completion_tokens=50,
                content_blocks=[tool_use_block]
            )
        else:
            phone_token = phone_token_box[0]
            
            # Second turn: verify that the tool result was returned to Claude tokenized!
            tool_result_msg = messages[-1]["content"]
            assert isinstance(tool_result_msg, list)
            assert tool_result_msg[0]["type"] == "tool_result"
            assert "9988776655" not in tool_result_msg[0]["content"]
            assert phone_token in tool_result_msg[0]["content"]
            
            # Dynamically parse the name token generated by the PrivacyEngine
            import json
            tool_data = json.loads(tool_result_msg[0]["content"])
            name_token = tool_data[0]["consumer_name"]
            
            # Second turn: Claude returns final text response containing tokens
            text_block = TextBlock(
                text=f"The customer name is {name_token} and phone is {phone_token}.",
                type="text"
            )
            return LLMResponse(
                content=f"The customer name is {name_token} and phone is {phone_token}.",
                prompt_tokens=150,
                completion_tokens=40,
                content_blocks=[text_block]
            )
            
    # Mocking standard generate_response fallback just in case
    async def mock_generate_response(*args, **kwargs):
        return LLMResponse("Fallback response", 10, 10)
        
    with unittest.mock.patch("conversation.manager.stdio_client", return_value=mock_stdio), \
         unittest.mock.patch("conversation.manager.ClientSession", return_value=mock_mcp_session), \
         unittest.mock.patch.object(conversation_manager._llm_manager._provider, "generate", side_effect=mock_generate), \
         unittest.mock.patch.object(conversation_manager._llm_manager, "generate_response", side_effect=mock_generate_response):
         
        # Execute the process message method
        res = await conversation_manager.process_message(
            session_id=session_id,
            content="Get me the billing transaction details of mobile_no 9988776655",
            role="user"
        )
        
        # Verify result detokenization for UI
        # "Rohan Sen" is the real value mapped to `<//NAME-yyyy//>` during tool output encryption
        assert "The customer name is Rohan Sen and phone is 9988776655." in res.response_content
        
        # Verify that call_tool was called with decrypted parameters (the real mobile_no, not the token!)
        mock_mcp_session.call_tool.assert_called_once()
        args, kwargs = mock_mcp_session.call_tool.call_args
        assert kwargs["arguments"]["sql"] == "SELECT consumer_name, mobile_no FROM consumer_master WHERE mobile_no = '9988776655'"

        # Verify that the DB contains the tokenized message
        from conversation.models.message import ChatMessage
        messages = await conversation_manager._history_manager.get_complete_history(session_id)
        assistant_db_msg = [m for m in messages if m.role == "assistant"][0]
        assert "9988776655" not in assistant_db_msg.content

        # Test session_detail_view GET to confirm it detokenizes before sending JSON to the user
        from django.test import RequestFactory
        import json
        
        factory = RequestFactory()
        req = factory.get(f"/api/sessions/{session_id}/")
        
        from conversation.controller import session_detail_view
        response = await session_detail_view(req, session_id)
        assert response.status_code == 200
        
        body = json.loads(response.content)
        history_item = [h for h in body["history"] if h["role"] == "assistant"][0]
        assert "The customer name is Rohan Sen and phone is 9988776655." in history_item["content"]
        assert "_privacy_state" not in body["memory"]


def test_encrypt_tool_result_structured():
    """Test that encrypt_tool_result correctly encrypts structured database results."""
    from conversation.privacy_engine import PrivacyEngine
    from conversation.manager import encrypt_tool_result
    
    engine = PrivacyEngine()
    
    db_result = {
        "success": True,
        "columns": ["consumer_name", "mobile_no", "feeder_id"],
        "rows": [["Rohan Sen", "9988776655", 123]]
    }
    
    import json
    res_str = encrypt_tool_result(json.dumps(db_result), engine)
    res_dict = json.loads(res_str)
    
    # Check that name and phone were tokenized
    row = res_dict["rows"][0]
    assert "<//NAME-" in row[0]
    assert "<//PHONE-" in row[1]
    assert row[2] == 123
    
    # Check that detokenizing works
    detok = engine.detokenize_text(row[0])
    assert detok == "Rohan Sen"
    detok_phone = engine.detokenize_text(row[1])
    assert detok_phone == "9988776655"
